-- MySQL Script generated by MySQL Workbench
-- Fri Aug 15 18:45:39 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mytennisapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mytennisapp` ;
CREATE SCHEMA IF NOT EXISTS `mytennisapp` DEFAULT CHARACTER SET utf8 ;
USE `mytennisapp` ;

-- -----------------------------------------------------
-- Table `mytennisapp`.`Home`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`Home` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`Home` (
  `homeID` INT NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `postCode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`homeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`Contact` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`Contact` (
  `contactID` INT NOT NULL AUTO_INCREMENT,
  `cellularPhone` VARCHAR(45) NULL,
  `workPhone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`contactID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`PlayerLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`PlayerLevel` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`PlayerLevel` (
  `playerLevelID` INT NOT NULL,
  `generalReference` VARCHAR(45) NOT NULL,
  `levelWithinReference` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`playerLevelID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`CoachLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`CoachLevel` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`CoachLevel` (
  `coachLevelID` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `group` VARCHAR(45) NULL,
  PRIMARY KEY (`coachLevelID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`User` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `contactID` INT NULL,
  `homeID` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NULL,
  `birthDate` DATE NULL,
  `federationNumber` VARCHAR(45) NULL,
  `coachLevelID` INT NULL,
  `playerLevelID` INT NULL,
  `activated` TINYINT(1) NOT NULL DEFAULT 0,
  `activationHash` VARCHAR(512) NULL,
  `activationMailSent` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`userID`),
  INDEX `fk_User_Home1_idx` (`homeID` ASC),
  INDEX `fk_User_Contact1_idx` (`contactID` ASC),
  UNIQUE INDEX `contactID_UNIQUE` (`contactID` ASC),
  INDEX `fk_User_PlayerLevel_idx` (`playerLevelID` ASC),
  INDEX `fk_User_CoachLevel_idx` (`coachLevelID` ASC),
  CONSTRAINT `fk_User_Home1`
    FOREIGN KEY (`homeID`)
    REFERENCES `mytennisapp`.`Home` (`homeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Contact1`
    FOREIGN KEY (`contactID`)
    REFERENCES `mytennisapp`.`Contact` (`contactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_PlayerLevel`
    FOREIGN KEY (`playerLevelID`)
    REFERENCES `mytennisapp`.`PlayerLevel` (`playerLevelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_CoachLevel`
    FOREIGN KEY (`coachLevelID`)
    REFERENCES `mytennisapp`.`CoachLevel` (`coachLevelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`SponsorAthleteRelationshipType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`SponsorAthleteRelationshipType` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`SponsorAthleteRelationshipType` (
  `relationshipTypeId` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`relationshipTypeId`),
  UNIQUE INDEX `label_UNIQUE` (`label` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`Sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`Sponsor` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`Sponsor` (
  `sponsorID` INT NOT NULL,
  `athleteID` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `relationshipType` INT NOT NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`sponsorID`, `athleteID`, `startDate`),
  INDEX `fk_Sponsor_User2_idx` (`athleteID` ASC),
  INDEX `fk_Sponsor_relationshipType_idx` (`relationshipType` ASC),
  CONSTRAINT `fk_Sponsor_User1`
    FOREIGN KEY (`sponsorID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sponsor_User2`
    FOREIGN KEY (`athleteID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sponsor_relationshipType`
    FOREIGN KEY (`relationshipType`)
    REFERENCES `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`Club` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`Club` (
  `clubID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `homeID` INT NOT NULL,
  `contactID` INT NOT NULL,
  `adminUserID` INT NOT NULL,
  PRIMARY KEY (`clubID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Club_Home1_idx` (`homeID` ASC),
  INDEX `fk_Club_Contact1_idx` (`contactID` ASC),
  INDEX `fk_Club_User1_idx` (`adminUserID` ASC),
  CONSTRAINT `fk_Club_Home1`
    FOREIGN KEY (`homeID`)
    REFERENCES `mytennisapp`.`Home` (`homeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_Contact1`
    FOREIGN KEY (`contactID`)
    REFERENCES `mytennisapp`.`Contact` (`contactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_User1`
    FOREIGN KEY (`adminUserID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`UserType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`UserType` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`UserType` (
  `userTypeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(150) NULL,
  PRIMARY KEY (`userTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`ClubHasUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`ClubHasUser` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`ClubHasUser` (
  `clubHasUserID` INT NOT NULL AUTO_INCREMENT,
  `clubID` INT NOT NULL,
  `userID` INT NOT NULL,
  `userTypeID` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  INDEX `fk_Club_has_User_User1_idx` (`userID` ASC),
  INDEX `fk_Club_has_User_Club1_idx` (`clubID` ASC),
  PRIMARY KEY (`clubHasUserID`),
  UNIQUE INDEX `uniqueCombination` (`clubID` ASC, `userID` ASC, `userTypeID` ASC, `startDate` ASC),
  INDEX `fk_UserType1_idx` (`userTypeID` ASC),
  CONSTRAINT `fk_Club_has_User_Club1`
    FOREIGN KEY (`clubID`)
    REFERENCES `mytennisapp`.`Club` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_has_User_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserType1`
    FOREIGN KEY (`userTypeID`)
    REFERENCES `mytennisapp`.`UserType` (`userTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`MainCoach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`MainCoach` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`MainCoach` (
  `coachID` INT NOT NULL,
  `athleteID` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `clubID` INT NOT NULL,
  PRIMARY KEY (`coachID`, `athleteID`, `startDate`),
  INDEX `fk_MainCoach_User2_idx` (`athleteID` ASC),
  INDEX `fk_MainCoach_Club1_idx` (`clubID` ASC),
  CONSTRAINT `fk_MainCoach_User1`
    FOREIGN KEY (`coachID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MainCoach_User2`
    FOREIGN KEY (`athleteID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MainCoach_Club1`
    FOREIGN KEY (`clubID`)
    REFERENCES `mytennisapp`.`Club` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`PracticeSession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`PracticeSession` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`PracticeSession` (
  `practiceSessionID` INT NOT NULL AUTO_INCREMENT,
  `coachID` INT NOT NULL,
  `clubID` INT NOT NULL,
  `activePracticeSession` TINYINT(1) NOT NULL DEFAULT TRUE,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `groupLevel` INT NULL,
  `dayOfWeek` INT NOT NULL,
  PRIMARY KEY (`practiceSessionID`),
  INDEX `fk_PracticeSession_Club1_idx` (`clubID` ASC),
  INDEX `fk_PraticeSession_Club2_idx` (`coachID` ASC),
  CONSTRAINT `fk_PracticeSession_Club1`
    FOREIGN KEY (`clubID`)
    REFERENCES `mytennisapp`.`Club` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PraticeSession_Club2`
    FOREIGN KEY (`coachID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`PracticeSessionHasAthlete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`PracticeSessionHasAthlete` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`PracticeSessionHasAthlete` (
  `practiceSessionID` INT NOT NULL,
  `athleteID` INT NOT NULL,
  PRIMARY KEY (`practiceSessionID`, `athleteID`),
  INDEX `fk_PracticeSession_has_User_User1_idx` (`athleteID` ASC),
  INDEX `fk_PracticeSession_has_User_PracticeSession1_idx` (`practiceSessionID` ASC),
  CONSTRAINT `fk_PracticeSession_has_User_PracticeSession1`
    FOREIGN KEY (`practiceSessionID`)
    REFERENCES `mytennisapp`.`PracticeSession` (`practiceSessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PracticeSession_has_User_User1`
    FOREIGN KEY (`athleteID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`PracticeSessionHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`PracticeSessionHistory` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`PracticeSessionHistory` (
  `practiceSessionHistoryID` INT NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `date` DATE NOT NULL,
  `coachID` INT NOT NULL,
  `clubID` INT NOT NULL,
  PRIMARY KEY (`practiceSessionHistoryID`),
  INDEX `fk_PracticeSessionHistory_User1_idx` (`coachID` ASC),
  INDEX `fk_PracticeSessionHistory_Club1_idx` (`clubID` ASC),
  CONSTRAINT `fk_PracticeSessionHistory_User1`
    FOREIGN KEY (`coachID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PracticeSessionHistory_Club1`
    FOREIGN KEY (`clubID`)
    REFERENCES `mytennisapp`.`Club` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`PracticeSessionHistoryHasAthlete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`PracticeSessionHistoryHasAthlete` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`PracticeSessionHistoryHasAthlete` (
  `practiceSessionHistoryID` INT NOT NULL,
  `athleteID` INT NOT NULL,
  `attendanceType` INT NOT NULL,
  PRIMARY KEY (`practiceSessionHistoryID`, `athleteID`),
  INDEX `fk_PracticeSessionHistory_has_User_User1_idx` (`athleteID` ASC),
  INDEX `fk_PracticeSessionHistory_has_User_PracticeSessionHistory1_idx` (`practiceSessionHistoryID` ASC),
  CONSTRAINT `fk_PracticeSessionHistory_has_User_PracticeSessionHistory1`
    FOREIGN KEY (`practiceSessionHistoryID`)
    REFERENCES `mytennisapp`.`PracticeSessionHistory` (`practiceSessionHistoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PracticeSessionHistory_has_User_User1`
    FOREIGN KEY (`athleteID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`FederationClub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`FederationClub` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`FederationClub` (
  `federationClubID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  PRIMARY KEY (`federationClubID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`FederationTournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`FederationTournament` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`FederationTournament` (
  `federationTournamentID` INT NOT NULL,
  `level` VARCHAR(2) NOT NULL,
  `qualyStartDate` DATE NULL,
  `qualyEndDate` DATE NULL,
  `mainDrawStartDate` DATE NOT NULL,
  `mainDrawEndDate` DATE NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `surface` VARCHAR(45) NOT NULL,
  `accommodation` VARCHAR(45) NULL,
  `meals` INT NULL,
  `prizeMoney` INT NULL,
  `federationClubID` INT NOT NULL,
  PRIMARY KEY (`federationTournamentID`),
  INDEX `fk_FederationTournament_FederationClub1_idx` (`federationClubID` ASC),
  CONSTRAINT `fk_FederationTournament_FederationClub1`
    FOREIGN KEY (`federationClubID`)
    REFERENCES `mytennisapp`.`FederationClub` (`federationClubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`AgeBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`AgeBand` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`AgeBand` (
  `ageBandID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `maxAge` VARCHAR(45) NOT NULL,
  `minAge` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ageBandID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`TournamentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`TournamentType` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`TournamentType` (
  `variation` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `federationTournamentID` INT NOT NULL,
  INDEX `fk_TournamentType_FederationTournament1_idx` (`federationTournamentID` ASC),
  PRIMARY KEY (`variation`, `gender`, `federationTournamentID`),
  CONSTRAINT `fk_TournamentType_FederationTournament1`
    FOREIGN KEY (`federationTournamentID`)
    REFERENCES `mytennisapp`.`FederationTournament` (`federationTournamentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`FederationTournamentHasAgeBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`FederationTournamentHasAgeBand` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`FederationTournamentHasAgeBand` (
  `federationTournamentID` INT NOT NULL,
  `ageBandID` INT NOT NULL,
  PRIMARY KEY (`federationTournamentID`, `ageBandID`),
  INDEX `fk_FederationTournament_has_AgeBand_AgeBand1_idx` (`ageBandID` ASC),
  INDEX `fk_FederationTournament_has_AgeBand_FederationTournament1_idx` (`federationTournamentID` ASC),
  CONSTRAINT `fk_FederationTournament_has_AgeBand_FederationTournament1`
    FOREIGN KEY (`federationTournamentID`)
    REFERENCES `mytennisapp`.`FederationTournament` (`federationTournamentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FederationTournament_has_AgeBand_AgeBand1`
    FOREIGN KEY (`ageBandID`)
    REFERENCES `mytennisapp`.`AgeBand` (`ageBandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`AthleteGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`AthleteGroup` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`AthleteGroup` (
  `athleteGroupID` INT NOT NULL,
  `minAge` INT NULL,
  `maxAge` INT NULL,
  `minPlayerLevel` VARCHAR(45) NULL,
  `maxPlayerLevel` VARCHAR(45) NULL,
  `clubID` INT NOT NULL,
  PRIMARY KEY (`athleteGroupID`),
  INDEX `fk_AthleteGroup_Club1_idx` (`clubID` ASC),
  CONSTRAINT `fk_AthleteGroup_Club1`
    FOREIGN KEY (`clubID`)
    REFERENCES `mytennisapp`.`Club` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`CompetitivePlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`CompetitivePlan` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`CompetitivePlan` (
  `athleteGroupID` INT NOT NULL,
  `federationTournamentID` INT NOT NULL,
  INDEX `fk_CompetitivePlan_AthleteGroup1_idx` (`athleteGroupID` ASC),
  INDEX `fk_CompetitivePlan_FederationTournament1_idx` (`federationTournamentID` ASC),
  PRIMARY KEY (`athleteGroupID`, `federationTournamentID`),
  CONSTRAINT `fk_CompetitivePlan_AthleteGroup1`
    FOREIGN KEY (`athleteGroupID`)
    REFERENCES `mytennisapp`.`AthleteGroup` (`athleteGroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CompetitivePlan_FederationTournament1`
    FOREIGN KEY (`federationTournamentID`)
    REFERENCES `mytennisapp`.`FederationTournament` (`federationTournamentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mytennisapp`.`CompetitiveResultHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mytennisapp`.`CompetitiveResultHistory` ;

CREATE TABLE IF NOT EXISTS `mytennisapp`.`CompetitiveResultHistory` (
  `competitiveResultHistoryID` INT NOT NULL,
  `winnerUserID` INT NOT NULL,
  `loserUserID` INT NOT NULL,
  `score` VARCHAR(45) NOT NULL,
  `federationTournamentID` INT NOT NULL,
  PRIMARY KEY (`competitiveResultHistoryID`),
  INDEX `fk_CompetitiveResultHistory_FederationTournament1_idx` (`federationTournamentID` ASC),
  INDEX `fk_Winner_idx` (`winnerUserID` ASC),
  INDEX `fk_Loser_idx` (`loserUserID` ASC),
  CONSTRAINT `fk_CompetitiveResultHistory_FederationTournament1`
    FOREIGN KEY (`federationTournamentID`)
    REFERENCES `mytennisapp`.`FederationTournament` (`federationTournamentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Winner`
    FOREIGN KEY (`winnerUserID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loser`
    FOREIGN KEY (`loserUserID`)
    REFERENCES `mytennisapp`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO myTennisUser;
 DROP USER myTennisUser;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'myTennisUser' IDENTIFIED BY 'Tenis123';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mytennisapp`.* TO 'myTennisUser';
GRANT ALL ON `mytennisapp`.* TO 'myTennisUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mytennisapp`.`PlayerLevel`
-- -----------------------------------------------------
START TRANSACTION;
USE `mytennisapp`;
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (1, 'Elite', 'High Performance');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (2, 'Advanced', 'High');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (3, 'Advanced', 'Medium');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (4, 'Advanced', 'Low');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (5, 'Intermediate', 'High');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (6, 'Intermediate', 'Medium');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (7, 'Intermediate', 'Low');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (8, 'Recreational', 'High');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (9, 'Recreational', 'Low');
INSERT INTO `mytennisapp`.`PlayerLevel` (`playerLevelID`, `generalReference`, `levelWithinReference`) VALUES (10, 'Starter', 'Starter');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mytennisapp`.`CoachLevel`
-- -----------------------------------------------------
START TRANSACTION;
USE `mytennisapp`;
INSERT INTO `mytennisapp`.`CoachLevel` (`coachLevelID`, `description`, `group`) VALUES (0, 'No coach training', 'Other');
INSERT INTO `mytennisapp`.`CoachLevel` (`coachLevelID`, `description`, `group`) VALUES (1, 'Level 1 FPT', 'FPT');
INSERT INTO `mytennisapp`.`CoachLevel` (`coachLevelID`, `description`, `group`) VALUES (2, 'Level 2 FPT', 'FPT');
INSERT INTO `mytennisapp`.`CoachLevel` (`coachLevelID`, `description`, `group`) VALUES (3, 'Level 3 FPT', 'FPT');
INSERT INTO `mytennisapp`.`CoachLevel` (`coachLevelID`, `description`, `group`) VALUES (4, 'Other', 'Other');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mytennisapp`.`SponsorAthleteRelationshipType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mytennisapp`;
INSERT INTO `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`, `label`, `description`) VALUES (NULL, 'Parent', NULL);
INSERT INTO `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`, `label`, `description`) VALUES (NULL, 'Grand-parent', NULL);
INSERT INTO `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`, `label`, `description`) VALUES (NULL, 'Sibling', NULL);
INSERT INTO `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`, `label`, `description`) VALUES (NULL, 'Aunt/Uncle', NULL);
INSERT INTO `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`, `label`, `description`) VALUES (NULL, 'Sponsor', NULL);
INSERT INTO `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`, `label`, `description`) VALUES (NULL, 'Other (related)', NULL);
INSERT INTO `mytennisapp`.`SponsorAthleteRelationshipType` (`relationshipTypeId`, `label`, `description`) VALUES (NULL, 'Other (non-related)', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mytennisapp`.`UserType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mytennisapp`;
INSERT INTO `mytennisapp`.`UserType` (`userTypeID`, `name`, `description`) VALUES (NULL, 'coach', 'coach or technical director');
INSERT INTO `mytennisapp`.`UserType` (`userTypeID`, `name`, `description`) VALUES (NULL, 'athlete', NULL);
INSERT INTO `mytennisapp`.`UserType` (`userTypeID`, `name`, `description`) VALUES (NULL, 'sponsor', 'sponsor or relative of the athlete');

COMMIT;

